services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: thisisunsafe
      MYSQL_DATABASE: patchme
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    environment:
      DATABASE_URL: "mysql://root:thisisunsafe@db:3306/patchme"
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data: